//
// From tree-sitter-ledger/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

source_file ::=
	 ( journal_item | '\n'  )*

journal_item ::=
	 comment
	| block_comment
	| test
	| directive
	| xact

comment ::=
	 ( ( ';' | '#' | '%' | '|' | '*' ) '.'*'#x0A' )

block_comment ::=
	 'comment' ( whitespace '.'* )? '\n'  ( ( whitespace? '.'* )? '\n'  )* ( 'end' | 'end comment' | 'end' '.'* )

test ::=
	 'test' ( whitespace '.'* )? '\n'  ( ( whitespace? '.'* )? '\n'  )* ( 'end' | 'end test' | 'end' '.'* )

option ::=
	 ( '-' | '--' ) [^ =#x0A]+ ( ( whitespace | '=' ) option_value )? '\n' 

option_value ::=
	 '.'+

indented_line ::=
	 whitespace [^#x0A]+'#x0A'

directive ::=
	 option
	| account_directive
	| commodity_directive
	| tag_directive
	| word_directive '\n' 
	| char_directive '\n' 

account_directive ::=
	 'account' whitespace account '\n'  account_subdirective*

account_subdirective ::=
	 alias_subdirective
	| default_subdirective
	| note_subdirective
	| assert_subdirective
	| check_subdirective
	| whitespace 'eval' whitespace '.'+'#x0A'
	| whitespace 'payee' whitespace '.'+'#x0A'

commodity_directive ::=
	 'commodity' whitespace commodity '\n'  commodity_subdirective*

commodity_subdirective ::=
	 alias_subdirective
	| default_subdirective
	| format_subdirective
	| note_subdirective
	| whitespace 'nomarket' '\n' 

tag_directive ::=
	 'tag' whitespace '\p{L}'+'#x0A' ( assert_subdirective | check_subdirective )*

word_directive ::=
	 'include' whitespace filename
	| 'end'
	| 'alias' whitespace [^=]+ '=' '.'+
	| 'def' whitespace '.'+
	| 'year' whitespace [0-9]'{4}'
	| 'bucket' whitespace account

filename ::=
	 '.'+

char_directive ::=
	 check_in
	| check_out
	| 'A' whitespace account
	| 'Y' whitespace [0-9]'{4}'
	| 'N' whitespace commodity
	| 'D' whitespace amount
	| 'C' whitespace commodity whitespace? '=' whitespace? amount
	| 'P' whitespace date whitespace commodity whitespace? amount

alias_subdirective ::=
	 whitespace 'alias' whitespace '.'+'#x0A'

default_subdirective ::=
	 whitespace 'default' '\n' 

format_subdirective ::=
	 whitespace 'format' whitespace amount

note_subdirective ::=
	 whitespace 'note' whitespace '.'+'#x0A'

assert_subdirective ::=
	 whitespace 'assert' whitespace '.'+'#x0A'

check_subdirective ::=
	 whitespace 'check' whitespace '.'+'#x0A'

check_in ::=
	 ( 'i' | 'I' ) whitespace? date whitespace? time whitespace? account ( spacer whitespace? payee )?

check_out ::=
	 ( 'o' | 'O' ) whitespace? date whitespace? time

xact ::=
	 plain_xact
	| periodic_xact
	| automated_xact

plain_xact ::=
	 _xact_date ( whitespace status )? ( whitespace code )? ( whitespace payee )? ( note | '\n'  ) ( posting | whitespace note '\n'  )+

periodic_xact ::=
	 '~' whitespace interval ( note | '\n'  ) ( posting | whitespace note '\n'  )+

interval ::=
	 [eE][vV][eE][rR][yY][  ][dD][aA][yY]
	| [eE][vV][eE][rR][yY][  ][wW][eE][eE][kK]
	| [eE][vV][eE][rR][yY][  ][mM][oO][nN][tT][hH]
	| [eE][vV][eE][rR][yY][  ][qQ][uU][aA][rR][tT][eE][rR]
	| [eE][vV][eE][rR][yY][  ][yY][eE][aA][rR]
	| [eE][vV][eE][rR][yY]' '[0-9]+' '[dD][aA][yY][sS]
	| [eE][vV][eE][rR][yY]' '[0-9]+' '[wW][eE][eE][kK][sS]
	| [eE][vV][eE][rR][yY]' '[0-9]+' '[mM][oO][nN][tT][hH][sS]
	| [eE][vV][eE][rR][yY]' '[0-9]+' '[qQ][uU][aA][rR][tT][eE][rR][sS]
	| [eE][vV][eE][rR][yY]' '[0-9]+' '[yY][eE][aA][rR][sS]
	| [dD][aA][iI][lL][yY]
	| [wW][eE][eE][kK][lL][yY]
	| [bB][iI][wW][eE][eE][kK][lL][yY]
	| [mM][oO][nN][tT][hH][lL][yY]
	| [bB][iI][mM][oO][nN][tT][hH][lL][yY]
	| [qQ][uU][aA][rR][tT][eE][rR][lL][yY]
	| [yY][eE][aA][rR][lL][yY]

automated_xact ::=
	 '=' whitespace query ( note | '\n'  ) ( posting | whitespace note '\n'  )+

_xact_date ::=
	 date effective_date?

date ::=
	 _single_date

effective_date ::=
	 '=' _single_date

_dsep ::=
	 [-.\/]

_2d ::=
	 [0-9]'{1,2}'

_4d ::=
	 [0-9]'{4}'

_single_date ::=
	 _4d _dsep _2d _dsep _2d
	| _2d _dsep _2d _dsep _2d
	| _2d _dsep _2d

time ::=
	 [0-9]'{2}:'[0-9]'{2}:'[0-9]'{2}'

status ::=
	 '*'
	| '!'

code ::=
	 '(' [^)]* ')'

payee ::=
	 [^(*!#x0A][^*!#x0A]*

query ::=
	 [^#x0A]+

note ::=
	 ';' whitespace ( '[' effective_date ']' | [^#x5B][^=#x0A]* )

posting ::=
	 whitespace ( status whitespace? )? account ( spacer ( whitespace? amount )? ( whitespace? price )? ( whitespace? balance_assertion )? ( whitespace? note )? )? '\n' 

account ::=
	 ( account_name | '(' account_name ')' | '[' account_name ']' )

account_name ::=
	 [^ ;]('\S \S'|'\S')*

amount ::=
	 quantity
	| negative_quantity
	| ( quantity | negative_quantity ) whitespace? commodity
	| commodity whitespace? ( quantity | negative_quantity )

_quantity ::=
	 [0-9]([0-9., ]*[0-9])?

quantity ::=
	 '+'? _quantity

negative_quantity ::=
	 '-' _quantity

commodity ::=
	 '\p{L}'+
	| '\p{Sc}'
	| '"'[^"#x0A]*'"'

price ::=
	 ( '@' | '@@' ) whitespace? amount

balance_assertion ::=
	 '=' whitespace? ( amount )

whitespace ::=
	 ( ' ' | '\t'  )+

spacer ::=
	 '  '
	| '\t' 
	| ' \t'

