//
// From tree-sitter-eno/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

document ::=
	 _instruction*

_commentOrEmpty ::=
	 comment
	| _emptyLine

_elementOrFieldsetOrList ::=
	 _escapedOrUnescapedKey ( elementOperator | copyOperator token ) _endOfLine

_emptyLine ::=
	 [ #x09\uFEFF\u2060\u200B]*'#x0A'

_escapedOrUnescapedKey ::=
	 key
	| escapeOperator escapedKey escapeOperator

_escapedOrUnescapedSectionKey ::=
	 sectionKey
	| escapeOperator escapedKey escapeOperator

_instruction ::=
	 _commentOrEmpty
	| element
	| empty
	| field
	| fieldset
	| list
	| multilineField
	| section

comment ::=
	 ( commentOperator token? _endOfLine )+

continuation ::=
	 ( directContinuationOperator | spacedContinuationOperator ) token _endOfLine

element ::=
	 _elementOrFieldsetOrList

empty ::=
	 _escapedOrUnescapedKey _endOfLine

entry ::=
	 _escapedOrUnescapedKey entryOperator token? _endOfLine ( _commentOrEmpty* continuation )*

field ::=
	 _escapedOrUnescapedKey elementOperator token _endOfLine ( _commentOrEmpty* continuation )*
	| _escapedOrUnescapedKey elementOperator _endOfLine ( _commentOrEmpty* continuation )+

fieldset ::=
	 _elementOrFieldsetOrList ( _commentOrEmpty* entry )+

item ::=
	 itemOperator token? _endOfLine ( _commentOrEmpty* continuation )*

key ::=
	 [^`>:=<#x2D-#x23|\ #x09#x0A#x0B#x0C#x0D]|[^`>:=<#x2D-#x23|\ #x09#x0A#x0B#x0C#x0D][^:=<#x0A]*[^:=< #x09#x0A#x0B#x0C#x0D]

list ::=
	 _elementOrFieldsetOrList ( _commentOrEmpty* item )+

multilineField ::=
	 multilineFieldOperator multilineFieldKey _endOfLine multilineFieldValue? _multilineFieldEnd multilineFieldOperator multilineFieldKey _endOfLine

multilineFieldValue ::=
	 ( _multilineFieldLine _endOfLine )+

section ::=
	 _sectionDescend sectionOperator _escapedOrUnescapedSectionKey ( ( copyOperator | deepCopyOperator ) token )? _endOfLine _instruction* _sectionAscend

sectionKey ::=
	 [^`< #x09#x0A#x0B#x0C#x0D]|[^`< #x09#x0A#x0B#x0C#x0D][^<#x0A]*[^< #x09#x0A#x0B#x0C#x0D]

token ::=
	 '\S'|'\S'[^#x0A]*'\S'

directContinuationOperator ::=
	 '|'

spacedContinuationOperator ::=
	 '\\' 

commentOperator ::=
	 '>'

copyOperator ::=
	 '<'

deepCopyOperator ::=
	 '<<'

entryOperator ::=
	 '='

itemOperator ::=
	 '-'

elementOperator ::=
	 ':'

sectionOperator ::=
	 '#'+

