/*
Grammar originally from https://github.com/tree-sitter/tree-sitter-jsdoc
Converted by excuting:
	qjs json2ebnf.js
Then manualy fixing the problems reported by https://rr.red-dove.com/ui in a way to allow visualization (correctnes is not the priority now)
*/

document ::=  ( _begin ( description )?  (  tag )*  _end )

description ::=  ( _text (  ( _text |  inline_tag )  )*  )

tag ::=  ( ( (  tag_name_with_argument )  ( ( '{'  type '}'  )  )?  ( _expression )?  ( description )?  )  |  ( (  tag_name_with_type )  ( ( '{'  type '}'  )  )?  ( description )?  )  |  ( tag_name ( description )?  )  )

inline_tag ::=  ( '{'  tag_name description '}'  )

tag_name_with_argument ::=  (  ( '@access'  |  '@alias'  |  '@api'  |  '@augments'  |  '@borrows'  |  '@callback'  |  '@constructor'  |  '@event'  |  '@exports'  |  '@external'  |  '@fires'  |  '@function'  |  '@mixes'  |  '@name'  |  '@namespace'  |  '@param'  |  '@property'  )  )

tag_name_with_type ::=  (  ( '@return'  |  '@returns'  |  '@throw'  |  '@throws'  )  )

tag_name ::=  '@'[a-zA-Z_]+

_expression ::=  ( identifier |  member_expression |  path_expression |  qualified_expression )

qualified_expression ::=   (  ( identifier ':'  _expression )  )

path_expression ::=   (  ( identifier (  '/'  )  identifier )  )

member_expression ::=  ( _expression ( '.'  |  '#'  |  '~'  )  ( identifier |  qualified_expression )  )

identifier ::=  [a-zA-Z_$][a-zA-Z_$0-9]*

type ::=  [^}\n]+

_text ::=  (   (  [^*{}@\s][^*{}\n]*([^*/{}\n][^*{}\n]*'*'+)* )  )

_begin ::=  (  ( '/'  (  '*'  )*  )  )

_end ::=  '/'

