//
// From tree-sitter-beancount/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

beancount_file ::=
	 ( _skipped_lines | _dated_directives | _undated_directives )*

_skipped_lines ::=
	 [!&?%PSTCURM*#x23] '.'* '#x0A'([ #x0D#x09]+'#x0A')?
	| ':' '.'* '#x0A'([ #x0D#x09]+'#x0A')?
	| '#x0A'([ #x0D#x09]+'#x0A')?
	| ';.'* '#x0A'([ #x0D#x09]+'#x0A')?

_undated_directives ::=
	 include
	| option
	| plugin
	| popmeta
	| poptag
	| pushmeta
	| pushtag

include ::=
	 'include' string '#x0A'([ #x0D#x09]+'#x0A')?

option ::=
	 'option' string string '#x0A'([ #x0D#x09]+'#x0A')?

plugin ::=
	 'plugin' string string? '#x0A'([ #x0D#x09]+'#x0A')?

pushtag ::=
	 'pushtag' tag '#x0A'([ #x0D#x09]+'#x0A')?

poptag ::=
	 'poptag' tag '#x0A'([ #x0D#x09]+'#x0A')?

pushmeta ::=
	 'pushmeta' key_value '#x0A'([ #x0D#x09]+'#x0A')?

popmeta ::=
	 'popmeta' key '#x0A'([ #x0D#x09]+'#x0A')?

_dated_directives ::=
	 balance
	| close
	| commodity
	| custom
	| document
	| event
	| note
	| open
	| pad
	| price
	| transaction
	| query

balance ::=
	 date 'balance' account ( amount | amount_with_tolerance ) metadata? '#x0A'([ #x0D#x09]+'#x0A')?

close ::=
	 date 'close' account metadata? '#x0A'([ #x0D#x09]+'#x0A')?

commodity ::=
	 date 'commodity' currency metadata? '#x0A'([ #x0D#x09]+'#x0A')?

custom ::=
	 date 'custom' string ( string | date | account | bool | amount | _num_expr )* metadata? '#x0A'([ #x0D#x09]+'#x0A')?

document ::=
	 date 'document' account string tags_and_links? metadata? '#x0A'([ #x0D#x09]+'#x0A')?

event ::=
	 date 'event' string string metadata? '#x0A'([ #x0D#x09]+'#x0A')?

note ::=
	 date 'note' account string metadata? '#x0A'([ #x0D#x09]+'#x0A')?

open ::=
	 date 'open' account currency_list? string? metadata? '#x0A'([ #x0D#x09]+'#x0A')?

pad ::=
	 date 'pad' account account metadata? '#x0A'([ #x0D#x09]+'#x0A')?

price ::=
	 date 'price' currency amount metadata? '#x0A'([ #x0D#x09]+'#x0A')?

transaction ::=
	 date flag ( string string | string )? tags_and_links? metadata? postings '#x0A'([ #x0D#x09]+'#x0A')?

query ::=
	 date 'query' string string metadata? '#x0A'([ #x0D#x09]+'#x0A')?

cost ::=
	 '{' _cost_comp_list? '}'

total_cost ::=
	 '{{' _cost_comp_list? '}}'

_cost_comp_list ::=
	 _cost_comp ( ',' _cost_comp )*

_cost_comp ::=
	 '*'
	| date
	| string
	| compound_amount

compound_amount ::=
	 _num_expr? currency
	| _num_expr currency?
	| _num_expr? '#' _num_expr? currency

incomplete_amount ::=
	 _num_expr
	| currency

price_annotation ::=
	 '@' ( amount | incomplete_amount )?

total_price_annotation ::=
	 '@@' ( amount | incomplete_amount )?

posting ::=
	 '#x0A'[ #x0D#x09]+ flag? account ( amount | incomplete_amount )? ( cost | total_cost )? ( price_annotation | total_price_annotation )? ';.'*? metadata?

postings ::=
	 ( posting | '#x0A'[ #x0D#x09]+ ';.'* )+

tags_and_links ::=
	 ( '#x0A'[ #x0D#x09]+? ( tag | link ) )+

currency_list ::=
	 currency ( ',' currency )*

metadata ::=
	 ( '#x0A'[ #x0D#x09]+ key_value )+

key_value ::=
	 key ( string | account | date | currency | tag | bool | _num_expr | amount )?

amount ::=
	 _num_expr currency

amount_with_tolerance ::=
	 _num_expr '~' _num_expr currency

_num_expr ::=
	 number
	| paren_num_expr
	| unary_num_expr
	| binary_num_expr

paren_num_expr ::=
	 '(' _num_expr ')'

unary_num_expr ::=
	 '-' _num_expr | '+' _num_expr

binary_num_expr ::=
	 _num_expr '*' _num_expr
	| _num_expr '/' _num_expr
	| _num_expr '+' _num_expr
	| _num_expr '-' _num_expr

bool ::=
	 'TRUE'|'FALSE'

date ::=
	 [0-9][0-9][0-9][0-9][#x2D-/][0-9][0-9][#x2D-/][0-9][0-9]

key ::=
	 [a-z][a-zA-Z0-9#x2D-_]+':'

tag ::=
	 '#'[A-Za-z0-9#x2D-_/.]+

link ::=
	 '\^'[A-Za-z0-9#x2D-_/.]+

string ::=
	 '"'[^"]*'"'

currency ::=
	 [A-Z][A-Z0-9\'._#x2D-]"{0,22}"[A-Z0-9]

number ::=
	 ([0-9]+|[0-9][0-9,]+[0-9])('.'[0-9]*)?

flag ::=
	 [!&?%PSTCURM*#x23]

account ::=
	 ( [A-Z]|[^\x00-\x7F] [A-Za-z0-9#x2D-]|[^\x00-\x7F]* ( ':' [A-Z0-9]|[^\x00-\x7F] [A-Za-z0-9#x2D-]|[^\x00-\x7F]* )+ )

