//
// From tree-sitter-vue/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

component ::=
	 ( comment | element | template_element | script_element | style_element )*

_node ::=
	 comment
	| text
	| interpolation
	| element
	| template_element
	| script_element
	| style_element
	| erroneous_end_tag

element ::=
	 start_tag _node* ( end_tag | _implicit_end_tag )
	| self_closing_tag

template_element ::=
	 template_start_tag _node* end_tag

script_element ::=
	 script_start_tag raw_text? end_tag

style_element ::=
	 style_start_tag raw_text? end_tag

start_tag ::=
	 '<' _start_tag_name ( attribute | directive_attribute )* '>'

template_start_tag ::=
	 '<' _template_start_tag_name ( attribute | directive_attribute )* '>'

script_start_tag ::=
	 '<' _script_start_tag_name ( attribute | directive_attribute )* '>'

style_start_tag ::=
	 '<' _style_start_tag_name ( attribute | directive_attribute )* '>'

self_closing_tag ::=
	 '<' _start_tag_name ( attribute | directive_attribute )* '/>'

end_tag ::=
	 '</' _end_tag_name '>'

erroneous_end_tag ::=
	 '</' erroneous_end_tag_name '>'

attribute ::=
	 attribute_name ( '=' ( attribute_value | quoted_attribute_value ) )?

attribute_name ::=
	 [^<>"'=/ #x09#x0A#x0B#x0C#x0D]+

attribute_value ::=
	 [^<>"'= #x09#x0A#x0B#x0C#x0D]+

quoted_attribute_value ::=
	 "'"  [^']+? "'" 
	| '"'  [^"]+? '"' 

text ::=
	 _text_fragment
	| '{{'

interpolation ::=
	 '{{' _interpolation_text? '}}'

directive_attribute ::=
	 ( directive_name ( ':' ( directive_argument | directive_dynamic_argument ) )? | directive_shorthand ( directive_argument | directive_dynamic_argument ) ) directive_modifiers? ( '=' ( attribute_value | quoted_attribute_value ) )?

directive_name ::=
	 'v-'[^<>'"=/ #x09#x0A#x0B#x0C#x0D:.]+

directive_shorthand ::=
	 ':' | '@' | '#'

directive_argument ::=
	 [^<>"'/= #x09#x0A#x0B#x0C#x0D.]+

directive_dynamic_argument ::=
	 '[' directive_dynamic_argument_value? ']'

directive_dynamic_argument_value ::=
	 [^<>"'/= #x09#x0A#x0B#x0C#x0D#x5D]+

directive_modifiers ::=
	 ( '.' directive_modifier )+

directive_modifier ::=
	 [^<>"'/= #x09#x0A#x0B#x0C#x0D.]+

