//
// From tree-sitter-embedded-template/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

template ::=
	 ( directive | output_directive | comment_directive | graphql_directive | content )*

code ::=
	 ( [^%=_-]+|[%=_-] | '%%>' )+

content ::=
	 ( [^<]+|'<' | '<%%' )+

directive ::=
	 ( '<%' | '<%_' | '<%|' ) code? ( '%>' | '-%>' | '_%>' )

output_directive ::=
	 ( '<%=' | '<%==' | '<%|=' | '<%|==' | '<%-' ) code? ( '%>' | '-%>' | '=%>' )

comment_directive ::=
	 '<%#' code? '%>'

graphql_directive ::=
	 '<%graphql' code? '%>'

