//
// From tree-sitter-jsdoc/src/grammar.json
//
//
// EBNF to generate railroad diagram at 
//      (IPV6) https://www.bottlecaps.de/rr/ui
//      (IPV4) https://rr.red-dove.com/ui
//

document ::=
	 _begin description? tag* _end

description ::=
	 _text ( _text | inline_tag | _inline_tag_false_positive )*

tag ::=
	 tag_name_with_argument ( '{' type '}' )? _expression? description?
	| tag_name_with_type ( '{' type '}' )? description?
	| tag_name description?

inline_tag ::=
	 '{' tag_name description '}'

_inline_tag_false_positive ::=
	 '\{'[^@}]+'\}'?

tag_name_with_argument ::=
	 ( '@access' | '@alias' | '@api' | '@augments' | '@borrows' | '@callback' | '@constructor' | '@event' | '@exports' | '@external' | '@extends' | '@fires' | '@function' | '@mixes' | '@name' | '@namespace' | '@param' | '@property' | '@prop' | '@satisfies' | '@typedef' )

tag_name_with_type ::=
	 ( '@return' | '@returns' | '@throw' | '@throws' | '@type' )

tag_name ::=
	 '@'[a-zA-Z_]+

_expression ::=
	 identifier
	| optional_identifier
	| member_expression
	| path_expression
	| qualified_expression

qualified_expression ::=
	 identifier ':' _expression

path_expression ::=
	 identifier '/' identifier

member_expression ::=
	 _expression ( '.' | '#' | '~' ) ( identifier | qualified_expression )

optional_identifier ::=
	 '[' identifier ']'

identifier ::=
	 [a-zA-Z_$][a-zA-Z_$0-9]*

_text ::=
	 [^*{}@ #x09#x0A#x0B#x0C#x0D][^*{}#x0A]*([^*/{}#x0A][^*{}#x0A]*'\'*+)*

_begin ::=
	 ( '/' '*'* )

_end ::=
	 '/'

