/*
Grammar originally from https://github.com/tree-sitter/tree-sitter-embedded-template
Converted by excuting:
	qjs json2ebnf.js
Then manualy fixing the problems reported by https://www.bottlecaps.de/rr/ui in a way to allow visualization (correctnes is not the priority now)
*/

template ::=  (  ( directive |  output_directive |  comment_directive |  graphql_directive |  content )  )*

code ::=  ( ( [^%=_-]+|[%=_-] |  '%%>'  )  )+

content ::=   (  ( ( [^<]+|'<' |  '<%%'  )  )+  )

directive ::=  ( ( '<%'  |  '<%_'  )  code ( '%>'  |  '-%>'  |  '_%>'  )  )

output_directive ::=  ( ( '<%='  |  '<%-'  )  code ( '%>'  |  '-%>'  |  '=%>'  )  )

comment_directive ::=  ( '<%#'  (  code )  '%>'  )

graphql_directive ::=  ( '<%graphql'  code '%>'  )
